# Site settings
title: Ed&Vic
email: mail@edandvic.uk
description: > # this means to ignore newlines until "baseurl:"
  Ed & Vic
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://edandvic.uk" # the base hostname & protocol for your site
twitter_username: edandvic
github_username:  edandvic

# Build settings
markdown: kramdown
